### PR TITLE
Do not keep dispatching after block listener falls behind

### LINKED ISSUE #127: Intermittently failed test
confirmed_block_listener_test.go#TestCBLDispatcherFallsBehindHead test is intermittently failed
```
confirmed_block_listener_test.go:363: 
        	Error Trace:	/__w/firefly-transaction-manager/firefly-transaction-manager/internal/confirmations/confirmed_block_listener_test.go:363
        	Error:      	Not equal: 
        	            	expected: 0x16
        	            	actual  : 0x0
        	Test:       	TestCBLDispatcherFallsBehindHead
    confirmed_block_listener_test.go:364: 
        	Error Trace:	/__w/firefly-transaction-manager/firefly-transaction-manager/internal/confirmations/confirmed_block_listener_test.go:364
        	Error:      	Not equal: 
        	            	expected: ffcapi.BlockInfo{BlockNumber:(*fftypes.FFBigInt)(0xc00032b2a0), BlockHash:"e8e8e712dac233fef15570952dceb2d7db344ccf1160b2303d15d4729d90da8d", ParentHash:"6816e38b91d1c8c14f7bf5efb8bd1bb52ccdf6becfeedd6f8264a201c645fd99", TransactionHashes:[]string(nil)}
        	            	actual  : ffcapi.BlockInfo{BlockNumber:(*fftypes.FFBigInt)(0xc0002ef6a0), BlockHash:"33871602bb36b4356c35eccfc726180b740c4ddfa60b00dffda94035b45216e9", ParentHash:"3a27f1b98d1199ab4ef1ecc82576b5851095bbd2533851037815e94aef6c84bd", TransactionHashes:[]string(nil)}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -3,8 +3,6 @@
        	            	   neg: (bool) false,
        	            	-  abs: (big.nat) (len=1) {
        	            	-   (big.Word) 22
        	            	-  }
        	            	+  abs: (big.nat) <nil>
        	            	  }),
        	            	- BlockHash: (string) (len=64) "e8e8e712dac233fef15570952dceb2d7db344ccf[1160](https://github.com/hyperledger/firefly-transaction-manager/actions/runs/10023036755/job/27703489841#step:5:1161)b2303d15d4729d90da8d",
        	            	- ParentHash: (string) (len=64) "6816e38b91d1c8c14f7bf5efb8bd1bb52ccdf6becfeedd6f8264a201c645fd99",
        	            	+ BlockHash: (string) (len=64) "33871602bb36b4356c35eccfc726180b740c4ddfa60b00dffda94035b45216e9",
        	            	+ ParentHash: (string) (len=64) "3a27f1b98d1199ab4ef1ecc82576b5851095bbd2533851037815e94aef6c84bd",
        	            	  TransactionHashes: ([]string) <nil>
        	Test:       	TestCBLDispatcherFallsBehindHead
coverage: 96.3% of statements
panic: test timed out after 30s
running tests:
	TestCBLDispatcherFallsBehindHead (30s)
```

https://github.com/hyperledger/firefly-transaction-manager/actions/runs/10023036755/job/27703489841

### PR DESCRIPTION
**Pull request by peterbroadhurst**
Fixes #127 

When I spent time breaking down the test to remove timing conditions, I found I was driving the logic below the new `return` I added in invalid ways. So the `return` felt much better to leave the existing queue in flight, and then the dispatcher will still fall back to `getBlockByNumber`

### CODE REVIEW

File: internal/confirmations/confirmed_block_listener.go [hunk 1]
```diff
@@ -194,12 +194,12 @@ func (cbl *confirmedBlockListener) processBlockNotification(block *apitypes.Bloc
 	var dispatchHead *apitypes.BlockInfo
 	if len(cbl.newHeadToAdd) > 0 {
 		// we've snuck in multiple notifications while the dispatcher is busy... don't add indefinitely to this list
-		if len(cbl.newHeadToAdd) > 10 /* not considered worth adding/explaining a tuning property for this */ {
+		if len(cbl.newHeadToAdd) >= 10 /* not considered worth adding/explaining a tuning property for this */ {
```
Comment (matthew1001) [inline internal/confirmations/confirmed_block_listener.go:197]: Looks good to me - just not sure why the change from `>` to `>=`?

**Review by matthew1001 — APPROVED** [review]

File: internal/confirmations/confirmed_block_listener.go (hunk 1 above)
Comment (peterbroadhurst) [reply internal/confirmations/confirmed_block_listener.go:197]: 11 just felt weird
